### ISSUE TITLE
RD Blade as alternative to AWS for seiscomp3 and CWB

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/hiperseis#31]

**Comment by Zephyrpony** [comment]
Jira task PST-216
https://gajira.atlassian.net/browse/PST-216

**Comment by niketchhajed** [comment]
After a long period of slow activity, we now have been given admin privileges on a limited part of the Blade hardware. Next steps are to explore the capability and assess the feasibility of using this infrastructure as PROD deployment for PST, both in short term and long term.

**Comment by niketchhajed** [comment]
Incident blocking this task: https://csc.service-now.com/selfservice/ticket_detail.do?sysparm_document_key=incident,b9b67428db2ac308d2a4ae994b96191e

**Comment by niketchhajed** [comment]
This is the latest servicenow ticket  https://csc.service-now.com/selfservice/ticket_detail.do?sysparm_document_key=sc_req_item,e21e3839dbe6c748f6cd8edf4b96195c tracking this task.
