### ISSUE TITLE
Station XMLs for missing ENGDAHL/ISC stations

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/hiperseis#39]
We have some additional stations in the ENGDHAL/ISC events that are not available in our seiscomp3.
For now, if possible, any workflow that requires station information should use the files that was emailed by ISC recently. Or for any statistical measure (like inputs to inversion) we can ignore those specific stations.

**Comment by alexgorb** [comment]
According to ISC some stations have information in FDSN database.

**Comment by Zephyrpony** [comment]
Jira task PST-223
https://gajira.atlassian.net/browse/PST-223
