### ISSUE TITLE
Tests missing

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/hiperseis#4]
https://github.com/GeoscienceAustralia/passive-seismic/tree/master/METADATA/SCRIPTS
https://github.com/GeoscienceAustralia/passive-seismic/tree/master/ASDFdatabase
https://github.com/GeoscienceAustralia/passive-seismic/tree/master/fix_ASDF_metadata

**Comment by zhang01GA** [comment]
no longer relevant
