### ISSUE TITLE
Apply travel time ellipticity correction to inversion inputs

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/hiperseis#48]
This is the ellipticity correction: https://github.com/GeoscienceAustralia/passive-seismic/issues/33
Should be applied to observed travel time in the output of #35 /  #44 .

**Comment by basaks** [comment]
@alexgorb how critical is this? Or are we ok for now?

We have the ellipticity correction working, so this should not be too difficult to implement, but the integration to the `cluster`ing code still have to be done.

**Comment by alexgorb** [comment]
Ellipticity correction is critical.

**Comment by basaks** [comment]
We should also package the fortran code of with `passive-seismic` for one step installation: #65.

**Comment by basaks** [comment]
This has been achieved in # 4537ea7bed13bf0f.

However, @alexgorb , we have to pay some attention to ellipticity correction parameters used in the [fortran code here](https://github.com/GeoscienceAustralia/ellip-corr). Specifically,[ the `ecolat` parameter has been defined as the `co-latitude`](https://github.com/GeoscienceAustralia/ellip-corr/blob/master/ellip/ellipcorr.f#L18) of the event location. However, and[ I have a TODO in the code](https://github.com/GeoscienceAustralia/passive-seismic/blob/4537ea7bed13bf0fdaeff5b1e25cefa40be01362/seismic/cluster/cluster.py#L377),  we need to make sure that the events that we are gathering arrivals from have latitudes defined in range (-90 to 90). 

From the TODO:
```
# TODO: check co-latitude definition
# no `ecolat` bounds check in fortran ellipcorr subroutine
# no `origin.latitude` bounds check in obspy
```
 Keeping this open for now until those are confirmed.

**Comment by basaks** [comment]
@alexgorb The above is important as if the events have origins defined using a different range of latitudes, will give wrong ellipticity correction as the [clustering code expects latitude defined in range [-90, 90] and converts the latitude to `co-latitude`](https://github.com/GeoscienceAustralia/passive-seismic/blob/4537ea7bed13bf0fdaeff5b1e25cefa40be01362/seismic/cluster/cluster.py#L380).
