### ISSUE TITLE
Temporary stations remaining tasks for Q1 deliverable

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/hiperseis#5]
- [ ] Temporary stations metadata generation - make sure can be ingested into sc3.  
- [ ] Ingestion of temporary stations time series data into sc3 after QA/QC - need to write complete functionality from available time series directory structure to sc3 ingestion. Check with `scart` that this data can be queried via sc3. This is dependent on the item above.

**Comment by basaks** [comment]
@rh-downunder Please collaborate with @outdoorpet .

**Comment by basaks** [comment]
While you guys are at it, please look into python3 support for the [`decode_anulog` functiion](https://github.com/GeoscienceAustralia/passive-seismic/blob/master/convert_logs/decode_datfile.py#L416). This is the only function which does not have python3 support in all of passive seismic package (except `antelope` events conversion, which has to be performed in propriatary python which has no python3 support and also needs to be worked in a corporate box).

**Comment by basaks** [comment]
Steps for this:
1. Stations metadata need to be prepared and inserted into seiscomp3. @outdoorpet has done a lot of work on this. Please build on that work and provide python3 support, and write appropriate tests.
2. Time series data needs to be read (possibly unique dir structure for each survey/network), QA/QC-ed (seisgram2k)  (@outdoorpet, @alexgorb  and Jason can help) , and inserted into seiscomp3 (@niketchhajed can help).
3. The rest of the checks are the same as pst-12 (again @niketchhajed can help).

**Comment by niketchhajed** [comment]
1. Temporary station xml provided by Rakib was tested for importing into the seiscomp3 inventory. The latest xml successfully imports in to the sc3 inventory.

2. Sample miniseed file from temporary station was tested for ingestion into the sc3 archive. The miniseed successfully imports into the SDS archive and is view able on scrttv upon further extraction using scart.

**Comment by rh-downunder** [comment]
We now have a process for incorporating temporary stations metadata (particularly response information) into stationxml files, which are required for ingesting temporary stations data into SC3 -- see comment above. At this stage we require input from @alexgorb regarding station response information that applies to the ANU surveys, e.g. the G7-2015 survey, which contains data of interest for the Q1 deliverable.

A detailed QA/QC of temporary stations data require functionality to be able to perform analysis based on cross-correlation of waveform data with that from reference stations. The current implementation of xcorr in the passive-seismic repository, along with corresponding results needs to be compared to those we received from Sima (at the ANU).

**Comment by zhang01GA** [comment]
no longer relevant
