### ISSUE TITLE
collect mtIsa instrument response and re-run picking

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/hiperseis#81]
At this point, we do not have the instrument response data for mtIsa seismometer/digitiser (Lennartz 3D-lite). For now, we have proceeded by putting the response code information obtained from https://ds.iris.edu/NRL/sensors/lennartz/RESP.XX.NS170..SHZ.LE-3DliteMkII.1.400 into the 7X station xml file, since SC3 needs this information to correctly import the station xml. Correctly here means the channel information should show up as Stream and not AuxStream. As far as picking is concerned, we should not have too much impact even if the instrument response is not exact.

Later when we have the correct instrument response, we will re-import the station xml file with the correct response xml nodes and reprocess the mtIsa seismic data for picking, etc.

**Comment by zhang01GA** [comment]
no longer relevant
