### ISSUE TITLE
run iLoc on the events generated for temporary surveys

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/hiperseis#84]
Refer: #79. This is an umbrella ticket for all temporary surveys.

**Comment by niketchhajed** [comment]
we are able to run iLoc on the skippy events. iLoc capabilities were discussed further with @alexgorb in terms of relocation vs phase defining.

**Comment by niketchhajed** [comment]
iLoc was run in phase-defining mode on extracted mtIsa events and the following statistics were plotted:

![image](https://user-images.githubusercontent.com/8789808/40162556-aea5a192-59f7-11e8-9a04-9e22687fc0fe.png)

**Comment by niketchhajed** [comment]
*there is a labeling mistake in the picture above. The red colour dots are for P arrivals, not S arrivals.

**Comment by niketchhajed** [comment]
Below is a plot of the phases after using the event relocation of iLoc on the same dataset. There is a marginal increase observed in the number of Pn and Sn phases compared to the pure-phase-defining iteration.
![image](https://user-images.githubusercontent.com/8789808/40219617-7920d934-5ab9-11e8-8bc3-5c7bb25a2344.png)

**Comment by zhang01GA** [comment]
no longer relevant
