### ISSUE TITLE
travel time tomographic inversion steps

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/hiperseis#85]
dumping an email conversation with @alexgorb about the steps involved in inversion:

1. Take the current(take ak135 or similar for first iteration) velocity model
2. trace the ray path for each event from source to receiver
3. obtain theoretical tt and subtract them from observed to get residuals
5. create parameter matrix from raylengths in each cell and residuals for data vector
6. invert matrix
7. get velocity corrections
8. create new model from velocity corrections
9. go to 1

**Comment by zhang01GA** [comment]
no longer relevant
