### ISSUE TITLE
inversion of seismogram to below the sediment layer in basins to improve receiver function results

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/hiperseis#92]
We have been exploring the paper [KTao-2014-gji.ggt515.pdf](https://github.com/GeoscienceAustralia/passive-seismic/files/2100469/KTao-2014-gji.ggt515.pdf). We also have the research codebase (matlab and bash) from the author. This technique needs to be applied to the receiver function dataset on mtIsa which has known basin features and we are observing similar reverberations in this corresponding regions.

**Comment by zhang01GA** [comment]
no longer relevant
