### ISSUE TITLE
picking of Australian and other relevant permanent stations cwb waveform data for ISC events

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/hiperseis#94]
So far, we were picking the cwb waveform data on a limited scale:

1. The event catalog was only the analyst reviewed events
2. To choose balance between experimentation and a realistic size for tt inversion imaging, we were only considering waveform data from years 2012 to 2017 since that is the period when we have highest quality waveform data.
3. We were only picking for stations which were already in the event catalog.

Now, we will expand the scope of picking for permanent stations dataset:

1. We will take the analyst reviewed plus the isc and engdahl events.
2. We will take a much bigger time frame from 1990 to 2017. Which means we will also be downloading ISC catalog for this timeframe.
3. We will pick all those permanent stations that lie within a given radius from the center of continent.

**Comment by niketchhajed** [comment]
The picking as described above has been triggered for years 1990 to September 2015 (ISC reviewed events are available upto this point). Will be triggering for October 2015 to end of 2017.

**Comment by niketchhajed** [comment]
Plot of the p and s residuals for permanent stations using the latest set of filtering frequencies and other improvements.

![p_res](https://user-images.githubusercontent.com/8789808/42795356-291315fa-89c7-11e8-9193-d8f7af13fc97.png)
![s_res](https://user-images.githubusercontent.com/8789808/42795360-2c97d2d8-89c7-11e8-8a30-a093408f763d.png)

**Comment by zhang01GA** [comment]
no longer relevant
