### ISSUE TITLE
receiver function analysis for mtIsa data with new set of "parameters"

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/hiperseis#95]
After discussion with @BabakHejrani, we are taking an improved approach for the receiver function study for mtIsa:

1. Use a frequency band of 0.06Hz to 1Hz for filtering the raw data.

2. Use a catalog with magnitude 5.0 to 7.0 in the survey timeframe.

3. Perform 2 iterations, one with source distance from center of continent as 15 degree to 90 degree and another iteration with the distance as 30 degree to 90 degree.

4. Perform 3 types of data cleaning:

- [ Take @BabakHejrani's RF filtering code (copied below for ready reference) in MATLAB and apply to the data:
`%Get a copy of the receiver functions ... 
rf1 = rf;

% Loop over all of them to calculate the sn, sn2, sn3 ... 
for i=1:length(rf1)
    % Find out where the P is ... 
    i1=floor(250/rf1(1).delta)+1;
   
    % The rms of the RF after P divided by the rms of the RF before P:
    sn(i)=rms(rf1(i).trace(i1:i1+500))/rms(rf1(i).trace(i1-500:i1-50));
    
   % The max amplitude of the RF (Gets crazy for Scandinavia ~ 1e14!) 
    sn2(i)=max(abs(rf1(i).trace));
    
   % The rms of whole RF (Gets crazy for Scandinavia ~ 1e13)
    sn3(i)=rms(rf1(i).trace);
end

%% If you sort the RFs, based on sn (high sn to low sn), then you can plot them and look at them to decide your criteria for filtering.   
% [sn,isort]=sort(sn);
% rf1=rf1(isort);

% These numbers are quite subjective ... 
rg=find(sn >= 2.0 & sn2 < 1 & sn3 < 0.2); 
rf1=rf1(rg);

`
] 

- [ Perform clustering (and PWS stacking as suggested by @rh-downunder) to remove incoherent RFs and increase the SNR respectively. ] 

- [ Filter out RFs for which the seismogram around the theoretical tt time window doesn't spit out an acceptable p-phase arrival]

**Comment by niketchhajed** [comment]
Additionally, there are 2 criteria to follow for clustering:

1. After applying clustering for similar waveforms in the set of RFs for a given stations, take the group (or cluster) whose cardinality is greater than a certain threshold percentage of the total number of RFs for that stations.
2. Also, the ratio of the cardinality of the group with highest number of RFs to the cardinality of the second highest group should be greater than a certain threshold.

The threshold mentioned in points above would be chosen based on experimentation across a sample of stations.

**Comment by zhang01GA** [comment]
no longer relevant
