### ISSUE TITLE
Calculating shifts in the GPS times of temporary station picks using nearby permanent station picks

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/hiperseis#96]
As per discussion with @BabakHejrani, the following steps will be taken to find GPS time-shifts in temporary stations:

1. Take 2 adjoining stations in the survey.
2. Take all the telesesmic events that hit both these stations during the survey.
3. Find the absolute value of difference between observed residuals across 2 stations for the same ray. Do this for all rays.
4. Plot the residual difference for the station pair.

These steps need to be performed for a few station pairs and the process automated for all pairs for a given survey.

**Comment by niketchhajed** [comment]
If there are jumps/spikes observed in the residual difference between station pairs, it points to GPS time shifts.

**Comment by niketchhajed** [comment]
In addition, find a permanent station near the survey and repeat the steps above with one of the stations as the permanent station.

**Comment by niketchhajed** [comment]
As per suggestion from @BabakHejrani, we can use the following approach to remove GPS time shift from the picks extracted from the temporary stations:

"
GPS time corrections on the fly (Highest priority, takes few days to code):
For the stations in each ANU's temporary deployments, subtract the arrival times of the teleseismic events from a nearby permanent station. 
If the residual is larger than a certain threshold (+/- 3 seconds) then remove that P-wave pick.
"

Changing the title of this issue accordingly.

**Comment by zhang01GA** [comment]
no longer relevant
